### PR TITLE
Post later toggle button

### LINKED ISSUE #68: Post Later toggle button fix
Currently, toggle button doesn't work as expected. Fix it to work as expected.

### PR DESCRIPTION
**Pull request by lucifer0987**
closes #68 
post later toggle button is fixed and by default, the posts are visible.

### CODE REVIEW

File: app/src/main/java/com/vatsal/kesarwani/therapy/Activity/AddPost.java [hunk 1]
```diff
@@ -78,12 +79,13 @@ protected void onCreate(Bundle savedInstanceState) {
         postLater.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
-                if(postLater.isChecked())
-                {
+                if (postLater.isChecked()) {
```
Comment (plazzy99) [inline app/src/main/java/com/vatsal/kesarwani/therapy/Activity/AddPost.java:82]: https://stackoverflow.com/a/11278528/12203379

Refer to this article to implement a listener instead of a variable to listen to the switch and modify UI accordingly.

**Review by plazzy99 — CHANGES_REQUESTED** [review]
Taking a variable for test case here is a suitable or preferred method.

**Comment by lucifer0987** [comment]
@plazzy99 made changes as you requested. Please review.

**Review by plazzy99 — COMMENTED** [review]
👍🏻 LGTM

Please confirm if you have tested it multiple times?
So that I can merge

**Comment by lucifer0987** [comment]
@plazzy99 Yes, I have tested it by making 3-4 posts. It works as expected.

**Review by plazzy99 — APPROVED** [review]
👍🏻
