### PR TITLE
Fixed recycler view refresh issue

### LINKED ISSUE #12: Recycler View recycle issue
Fix recycler view recycle issue that refreshes the list every time.

### PR DESCRIPTION
**Pull request by lucifer0987**
closes #12 
Fixed recycler view refresh issue for both cureFragment and chatFragment.

### CODE REVIEW

File: app/src/main/java/com/vatsal/kesarwani/therapy/Activity/ChatActivity.java [hunk 1]
```diff
@@ -134,6 +133,7 @@ public void onCancelled(@NonNull DatabaseError error) {
 
             }
         };
+
```
Comment (plazzy99) [inline app/src/main/java/com/vatsal/kesarwani/therapy/Activity/ChatActivity.java:136]: remember not to make changes on files, where you have not made any code change.

**Review by plazzy99 — APPROVED** [review]
👍🏻
